### ISSUE TITLE
In product page, when we hover over the but it now button then the text is coming of different colour as compared with the live theme.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Commonlines-Speed-work#1]
**Actual result:**
In product page, when we hover over the but it now button then the text is coming of different colour as compared with the live theme.
https://commonlines.com/collections/summer-sale-22/products/verde-pearls
![image](https://user-images.githubusercontent.com/102131636/189053868-580a402f-a922-456c-bdbb-e2ca9d5506cd.png)

**Expected result:**
When we hover over the buy it now then the text should be of same as live .
![image](https://user-images.githubusercontent.com/102131636/189054055-02b03aee-ec1d-48cc-80c2-c4c9d7e983db.png)

**Comment by devRitikTamrakar** [comment]
fixed

**Comment by sudhanshu0603** [comment]
ok, resolved
